### PR TITLE
feat: add `createMapper` convenience utility

### LINKED ISSUE #260: feat: is there a replacement for the mapState utility?
First of all, awesome work, super useful.

I successfully migrated Nuxt 2 stores using your library. I'm able to use `$accessor` but I feel like using state variable in components should be simplified. (eg: $accessor.submodule.property -> property). I've done that using mapState before using typed-vuex:
```ts
export default Vue.extend({
    computed: {
        // here is the magic
        ...mapState('submodule', ['property']),
    },
})
```
But we loose the type of the freshly computed property `property`. Is there a way to keep this sugar syntaxe (not redefine every computed property, aka keep an utility for this) without loosing the types?

I think this should be documented in a new `computed properties` section?

### PR DESCRIPTION
**Pull request by danielroe**
resolves #260

## 🔥 Notable changes

This PR adds a convenience helper function to allow you to easily map the accessor state/methods into your component.

```ts
import Vue from 'vue'

// Nuxt
import { accessorType } from '~/store'
const mapper = createMapper(accessorType)
// Vue
import { accessor } from './src/store'
const mapper = createMapper(accessor)

export default Vue.extend({
  computed: {
    // Direct mapping to a property
    ...mapper('name'),
    // or array of properties
    ...mapper(['name', 'email']),
    // or submodules
    ...mapper('submodule', ['name', 'email']),
  },
  methods: {
    // All your methods should be included in the methods object,
    // whether they are mutations, actions (or even a method returned
    // by a getter or stored in state)
    ...mapper('resetName'),
    resetEmail() {
      // You can access directly off your component instance
      console.log(this.name, this.email)
      this.resetName()
    },
  },
})
```

### CODE REVIEW

**Comment by RomainBillot** [comment]
Freaking insane ! Thanks ❤️

**Comment by MateiNenciu** [comment]
Great feature, but can this be extend to allow us to rename the props names? Like vuex does with mapGetters, etc ?

**Comment by danielroe** [comment]
Go for it - raise a PR with an example of what you mean 😊

**Comment by omnichronous** [comment]
This looks very cool, but I don't understand where to import `createMapper` from - it's not exported in `node_modules/typed-vuex/lib/index.d.ts`?

**Comment by omnichronous** [comment]
My bad, I was using an older version, thank you!

I also want to second [MateiNenciu](https://github.com/MateiNenciu)'s feature request, but I'll follow your suggestion to open a new issue for it.

**Pull request merged**
